### ISSUE TITLE
Bug report: "Hide sections conflicting with schedule" with no sections in schedule

### ISSUE THREAD

**Issue by ains-arch** [MuddCreates/hyperschedule#211]
When I have no classes added to the schedule, and I click the "Hide sections conflicting with schedule" toggle in Filters, I hit the error page. Have been able to reproduce a few times. This is in the beta version, and I'm on Firefox.

From the error page:
```{"fileName":"https://beta.hyperschedule.io/app.js","lineNumber":23,"columnNumber":86676,"message":"b is undefined"}```

I have added courses to my schedule in the past, and I think they're still saved in "Persistent user data (local)," but they're not currently displaying anywhere.

**Comment by mia1024** [comment]
Hi, 

Thank you for the bug report. Can you check if the issue can still be reproduced on https://nightly.hyperschedule.io/

**Comment by ains-arch** [comment]
I am unable to reproduce but I think the issue is more connected to having had schedules saved and available in the drop down menu, but somehow having none of them actually selected. I can't reproduce that on nightly, nor can I reproduce it on beta again now that I've selected one of the schedules.

**Comment by mia1024** [comment]
Seems like this was related to a bug that was recently fixed. We have pushed the fix to beta.
