### ISSUE TITLE
New license disclaimer misstates acceptable usage of the software

### ISSUE THREAD

**Issue by jterwilliger30** [MuddCreates/hyperschedule#216]
Regarding the new license, I think the disclaimer provided below misstates the license a bit:

"By continuing using this program, you acknowledge that you are not involved in the design, construction, operation, maintenance, or training of any military facility."

As written, this would apply to 5C folks who are national guard members, or veterans with existing non-active duty service obligations. To accurately convey the BSD3 no-military clause, it should probably read something more like:

"By continuing using this program, you acknowledge that your usage of this software is not involved in the design, construction, operation, maintenance, or training of any military facility."

**Comment by mia1024** [comment]
Fixed 443dc0f
