### ISSUE TITLE
Update Test Data for FA2024

### ISSUE THREAD

**Issue by CoolSpy3** [MuddCreates/hyperschedule#218]
Currently, the data loaded by `docker-load-db` includes the data from SP2024, [but the code is configured to search for data from FA2024](https://github.com/hyperschedule/hyperschedule/blob/5c1963825f5dfeb7ec998f03a6a8b9f2464c91bd/shared/api/current-term.ts#L18-L21). As a result, local testing fails with `[Error: ENOENT: no such file or directory, open '/srv/hyperschedule/data/FA2024/course-areas-description.json']`.

**Comment by mia1024** [comment]
That process is unfortunately manual. We'll update it soon but it will take a while

**Comment by mia1024** [comment]
For the time being, you can test things by temporarily changing the value coded in [CURRENT_TERM](https://github.com/hyperschedule/hyperschedule/blob/v2/shared/api/current-term.ts) to SP2024 on your local machine.

**Comment by mia1024** [comment]
Sorry for the delay. This should be fixed by d8e5ed7

**Comment by CoolSpy3** [comment]
Confirmed! Thank you!
