### ISSUE TITLE
Requesting code to scrape courses

### ISSUE THREAD

**Issue by abizermamnoon** [MuddCreates/hyperschedule#225]
Hi,

I am trying to create an LLM chatbot to interact with the course catalogue. My first step is to scrape the course catalogue. How did you go about doing that?

**Comment by stuxf** [comment]
Hi there,

We don't scrape the course catalog, we get data directly from the school registrar. Because this isn't really an issue about Hyperschedule, I'll be closing it. Feel free to email us if you'd like.

**Comment by abizermamnoon** [comment]
Hi, which school registrar do you get the data from?
